version: '2'
services:
  spring-boot:
    image: doku-akademi:latest
    container_name: doku-akademi
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - doku-akademi-network
    depends_on:
    - database
    ports:
    - 8090:8090
    volumes:
      - ./docker/volume:/apps/demo-docker/volume

  database:
    image: postgresql
    container_name: postgresql
    build:
      context: docker
      dockerfile: Dockerfile
    networks:
    - doku-akademi-network
    expose:
      - 5432

networks:
  doku-akademi-network:
    driver: bridge